name: nix-build-on-demand-docker
on:
  workflow_dispatch:

jobs:
  build-default-image:
    name: Build default image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-21.11
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - name: Check nix.conf
        run: cat /etc/nix/nix.conf
      - name: Register binfmt
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Test binfmt availability
        run: |
          cat /proc/sys/fs/binfmt_misc/qemu-aarch64
      - name: Build SD Image
        run: |
          nix-build '<nixpkgs/nixos>'  \
            -A config.system.build.sdImage \
            -I nixos-config=./sd-image.nix \
            --argstr system aarch64-linux \
            --option sandbox false
      - uses: actions/upload-artifact@v2
        with:
          name: sd-image.img
          path: ./result/sd-image/*.img*
